# Generated by Django 5.0.6 on 2024-11-06 17:22

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('id_bienes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_de_identificacion', models.CharField(error_messages={'unique': 'Ya existe un bien con este número de identificación.'}, max_length=50, unique=True)),
                ('incorporacion', models.IntegerField()),
                ('desincorporacion', models.IntegerField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, choices=[('Operativo', 'Operativo'), ('No', 'No Operativo')], default='Operativo', max_length=50, null=True)),
                ('observacion', models.CharField(max_length=255)),
                ('archivo_multimedia', models.FileField(blank=True, null=True, upload_to='archivos_multimedia/')),
                ('fecha_de_registro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoDeMovimiento',
            fields=[
                ('id_concepto_de_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamentos', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_departamento', models.CharField(max_length=50)),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_codigo', message='El código debe contener solo números', regex='^[0-9]+$')])),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RolDelUsuario',
            fields=[
                ('id_rol_del_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('ADMIN_BIENES', 'Administrador de Bienes'), ('USUARIO_ESTANDAR', 'Usuario Estándar')], max_length=20, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SeccionSubgrupo',
            fields=[
                ('id_seccion_subgrupo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBien',
            fields=[
                ('id_tipo_bien', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(default=1)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Bien',
                'verbose_name_plural': 'Tipos de Bienes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TiposDeEvento',
            fields=[
                ('id_tipos_de_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('REGISTRO', 'Registro Inicial'), ('INCORPORACION', 'Incorporación'), ('ASIGNACION', 'Asignación'), ('TRASLADO_TEMPORAL', 'Traslado Temporal'), ('TRASLADO_PERMANENTE', 'Traslado Permanente'), ('DESINCORPORACION', 'Desincorporación'), ('MANTENIMIENTO', 'Entrada a Mantenimiento'), ('FIN_MANTENIMIENTO', 'Salida de Mantenimiento'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución de Préstamo'), ('RESGUARDO', 'Entrada a Resguardo'), ('SALIDA_RESGUARDO', 'Salida de Resguardo'), ('BAJA', 'Baja Definitiva')], max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeSolicitud',
            fields=[
                ('id_tipos_de_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=50, null=True, unique=True)),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('fecha_de_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('eliminado', 'Eliminado')], default='activo', max_length=20, null=True)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('bienes_asignados', models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='aplicacion.bienes')),
                ('id_departamentos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.departamentos')),
                ('id_rol_del_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.roldelusuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='bienes',
            name='id_concepto_de_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.conceptodemovimiento'),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDeBienes',
            fields=[
                ('id_asignacion_bienes', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_asignada', models.IntegerField()),
                ('fecha_de_asignacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_fin_temporal', models.DateField(blank=True, null=True)),
                ('id_bienes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
                ('id_departamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id_descripcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('regular', 'Regular'), ('no existe', 'No existe')], max_length=20)),
                ('id_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
            ],
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id_especificacion', models.AutoField(primary_key=True, serialize=False)),
                ('especificacion', models.CharField(max_length=100)),
                ('descripcion_especificacion', models.CharField(max_length=255)),
                ('id_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
            ],
        ),
        migrations.AddField(
            model_name='bienes',
            name='id_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.grupo'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='aplicacion.conversacion')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientosBienes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('estado_solicitud', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('bien_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
                ('departamento_destino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recibidos', to='aplicacion.departamentos')),
                ('departamento_solicitante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_solicitados', to='aplicacion.departamentos')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bienes',
            name='id_seccion_subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.seccionsubgrupo'),
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitudes', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('cantidad_solicitada', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_maxima_traslado', models.DateField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('bien_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
                ('departamento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_destino', to='aplicacion.departamentos')),
                ('departamento_solicitante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_hechas', to='aplicacion.departamentos')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipos_de_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tiposdesolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='aplicacion.solicitudes')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.IntegerField(default=0)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('cantidad_asignada', models.IntegerField(default=0)),
                ('cantidad_prestada', models.IntegerField(default=0)),
                ('cantidad_en_mantenimiento', models.IntegerField(default=0)),
                ('cantidad_desincorporada', models.IntegerField(default=0)),
                ('cantidad_resguardada', models.IntegerField(default=0)),
                ('bien_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
            ],
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id_subgrupo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='seccionsubgrupo',
            name='id_subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.subgrupo'),
        ),
        migrations.AddField(
            model_name='bienes',
            name='id_subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.subgrupo'),
        ),
        migrations.AddField(
            model_name='bienes',
            name='tipo_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.tipobien'),
        ),
        migrations.CreateModel(
            name='HistorialBienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('cantidad_afectada', models.IntegerField()),
                ('bien_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.bienes')),
                ('departamento_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_destino', to='aplicacion.departamentos')),
                ('departamento_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_origen', to='aplicacion.departamentos')),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_tipos_de_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tiposdeevento')),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
