# Generated by Django 5.0.6 on 2024-11-06 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_mensaje_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='borrado_para',
            field=models.ManyToManyField(blank=True, related_name='mensajes_borrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
