# Generated by Django 5.0.6 on 2024-11-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_mensaje_borrado_para'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='asignaciondebienes',
            table='asignaciones_bienes',
        ),
        migrations.AlterModelTable(
            name='bienes',
            table='bienes',
        ),
        migrations.AlterModelTable(
            name='conceptodemovimiento',
            table='conceptos_movimiento',
        ),
        migrations.AlterModelTable(
            name='departamentos',
            table='departamentos',
        ),
        migrations.AlterModelTable(
            name='descripcion',
            table='descripciones',
        ),
        migrations.AlterModelTable(
            name='especificacion',
            table='especificaciones',
        ),
        migrations.AlterModelTable(
            name='movimientosbienes',
            table='movimientos_bienes',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones',
        ),
        migrations.AlterModelTable(
            name='roldelusuario',
            table='roles_usuario',
        ),
        migrations.AlterModelTable(
            name='seccionsubgrupo',
            table='secciones_subgrupo',
        ),
        migrations.AlterModelTable(
            name='solicitudes',
            table='solicitudes',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
        migrations.AlterModelTable(
            name='subgrupo',
            table='subgrupos',
        ),
        migrations.AlterModelTable(
            name='tiposdeevento',
            table='tipos_evento',
        ),
        migrations.AlterModelTable(
            name='tiposdesolicitud',
            table='tipos_solicitud',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
