# Generated by Django 5.0.6 on 2024-11-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_usuario_options_alter_asignaciondebienes_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='conversacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='borrado_para',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='emisor',
        ),
        migrations.DeleteModel(
            name='Conversacion',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
