# Generated by Django 5.0.6 on 2024-11-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_historialbienes_table_alter_tipobien_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grupo',
            table='grupos',
        ),
    ]
