# Generated by Django 5.0.6 on 2024-11-12 13:44

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_bienes_desincorporacion_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienes',
            name='desincorporacion',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='VES', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bienes',
            name='incorporacion',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='VES', max_digits=15),
        ),
    ]
