# Generated by Django 5.0.6 on 2024-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_bienes_desincorporacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienes',
            name='desincorporacion_currency',
        ),
        migrations.RemoveField(
            model_name='bienes',
            name='incorporacion_currency',
        ),
        migrations.AlterField(
            model_name='bienes',
            name='desincorporacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bienes',
            name='incorporacion',
            field=models.IntegerField(),
        ),
    ]
