# Generated by Django 5.0.6 on 2024-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_remove_bienes_desincorporacion_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienes',
            name='desincorporacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bienes',
            name='incorporacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
