# Generated by Django 5.0.6 on 2024-11-18 03:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_historialusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienes',
            name='desincorporacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bienes',
            name='incorporacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='El valor no puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='tiposdeevento',
            name='nombre',
            field=models.CharField(choices=[('REGISTRO', 'Registro Inicial'), ('INCORPORACION', 'Incorporación'), ('ASIGNACION', 'Asignación'), ('TRASLADO_TEMPORAL', 'Traslado Temporal'), ('TRASLADO_PERMANENTE', 'Traslado Permanente'), ('DESINCORPORACION', 'Desincorporación'), ('MANTENIMIENTO', 'Entrada a Mantenimiento'), ('FIN_MANTENIMIENTO', 'Salida de Mantenimiento'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución de Préstamo'), ('RESGUARDO', 'Entrada a Resguardo'), ('SALIDA_RESGUARDO', 'Salida de Resguardo'), ('BAJA', 'Baja Definitiva'), ('CAMBIO_CONCEPTO', 'Cambio de Concepto de Movimiento')], max_length=50, unique=True),
        ),
    ]
