# Generated by Django 5.0.6 on 2024-11-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_alter_bienes_incorporacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienes',
            name='desincorporacion',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='bienes',
            name='incorporacion',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
