# Generated by Django 5.0.6 on 2024-11-19 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0017_alter_bienes_desincorporacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id_gerencia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
                'db_table': 'gerencias',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['gerencia', 'codigo_departamento']},
        ),
        migrations.AlterField(
            model_name='asignaciondebienes',
            name='id_departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.departamentos'),
        ),
        migrations.AddField(
            model_name='asignaciondebienes',
            name='id_gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='departamentos',
            name='gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='historialbienes',
            name='gerencia_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_destino_gerencia', to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='historialbienes',
            name='gerencia_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_origen_gerencia', to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='movimientosbienes',
            name='gerencia_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recibidos_gerencia', to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='movimientosbienes',
            name='gerencia_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_solicitados_gerencia', to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='gerencia_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_destino_gerencia', to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='gerencia_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_hechas_gerencia', to='aplicacion.gerencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.gerencia'),
        ),
        migrations.AlterUniqueTogether(
            name='departamentos',
            unique_together={('gerencia', 'codigo_departamento'), ('gerencia', 'nombre_departamento')},
        ),
    ]
