# Generated by Django 5.0.6 on 2024-11-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0018_gerencia_alter_departamentos_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gerencia',
            new_name='UnidadOrganizacional',
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['UnidadOrganizacional', 'codigo_departamento']},
        ),
        migrations.AlterModelOptions(
            name='unidadorganizacional',
            options={'ordering': ['codigo'], 'verbose_name': 'Unidad Organizacional', 'verbose_name_plural': 'Unidades Organizacionales'},
        ),
        migrations.RenameField(
            model_name='asignaciondebienes',
            old_name='id_gerencia',
            new_name='id_UnidadOrganizacional',
        ),
        migrations.RenameField(
            model_name='departamentos',
            old_name='gerencia',
            new_name='UnidadOrganizacional',
        ),
        migrations.RenameField(
            model_name='unidadorganizacional',
            old_name='id_gerencia',
            new_name='id_unidad',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_gerencia',
            new_name='id_unidadOrganizacional',
        ),
        migrations.RemoveField(
            model_name='historialbienes',
            name='gerencia_destino',
        ),
        migrations.RemoveField(
            model_name='historialbienes',
            name='gerencia_origen',
        ),
        migrations.RemoveField(
            model_name='movimientosbienes',
            name='gerencia_destino',
        ),
        migrations.RemoveField(
            model_name='movimientosbienes',
            name='gerencia_solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='gerencia_destino',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='gerencia_solicitante',
        ),
        migrations.AddField(
            model_name='historialbienes',
            name='UnidadOrganizacional_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_destino_unidad', to='aplicacion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='historialbienes',
            name='UnidadOrganizacional_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_origen_unidad', to='aplicacion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='movimientosbienes',
            name='UnidadOrganizacional_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recibidos_unidad', to='aplicacion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='movimientosbienes',
            name='UnidadOrganizacional_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_solicitados_unidad', to='aplicacion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='UnidadOrganizacional_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_destino_unidad', to='aplicacion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='UnidadOrganizacional_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_hechas_unidad', to='aplicacion.unidadorganizacional'),
        ),
        migrations.AlterUniqueTogether(
            name='departamentos',
            unique_together={('UnidadOrganizacional', 'codigo_departamento'), ('UnidadOrganizacional', 'nombre_departamento')},
        ),
        migrations.AlterModelTable(
            name='unidadorganizacional',
            table='unidades_organizacionales',
        ),
    ]
