# Generated by Django 5.0.6 on 2024-11-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_rename_gerencia_unidadorganizacional_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialusuario',
            table='historial_usuarios',
        ),
    ]
