# Generated by Django 5.0.6 on 2024-11-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_alter_historialusuario_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='departamento_solicitante_id',
            new_name='departamento_solicitante',
        ),
    ]
