# Generated by Django 5.0.6 on 2024-11-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_rename_departamento_solicitante_id_solicitudes_departamento_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='departamento_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_hechas', to='aplicacion.departamentos'),
        ),
    ]
