# Generated by Django 5.0.6 on 2024-11-21 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0022_alter_solicitudes_departamento_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosbienes',
            name='departamento_destino_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recibidos', to='aplicacion.departamentos'),
        ),
        migrations.AlterField(
            model_name='movimientosbienes',
            name='departamento_solicitante_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_solicitados', to='aplicacion.departamentos'),
        ),
    ]
